#! /bin/bash

BOLD="$(tput bold)"

BLUE="$(tput setaf 4)"
BLUEB="$BLUE$BOLD"

GREEN="$(tput setaf 2)"
GREENB="$GREEN$BOLD"

AZURE="$(tput setaf 6)"
AZUREB="$AZURE$BOLD"

RED="$(tput setaf 1)"
REDB="$RED$BOLD"

PURPLE="$(tput setaf 5)"
PURPLEB="$PURPLE$BOLD"

YELLOW="$(tput setaf 3)"
YELLOWB="$YELLOW$BOLD"

WHITE="$(tput setaf 7)"
WHITEB="$WHITE$BOLD"

NORMAL="$(tput sgr0)"

file=$(basename "$0")
if [ "$file" = ".term_colors" ]; then
    echo -ne "${BLUE}normal blue$NORMAL\t"
    echo -e  "${BLUEB}bold blue$NORMAL"
    echo -ne "${RED}normal red$NORMAL\t"
    echo -e  "${REDB}bold red$NORMAL"
    echo -ne "${GREEN}normal green$NORMAL\t"
    echo -e  "${GREENB}bold green$NORMAL"
    echo -ne "${YELLOW}normal yellow$NORMAL\t"
    echo -e  "${YELLOWB}bold yellow$NORMAL"
    echo -ne "${AZURE}normal azure$NORMAL\t"
    echo -e  "${AZUREB}bold azure$NORMAL"
    echo -ne "${PURPLE}normal purple$NORMAL\t"
    echo -e  "${PURPLEB}bold purple$NORMAL"
    echo -ne "${WHITE}normal white$NORMAL\t"
    echo -e  "${WHITEB}bold white$NORMAL"
fi

# vim: ft=sh
