#! /bin/bash

BOLD="$(tput bold)"

BLUE="$(tput setf 1)"
BLUEB="$BLUE$BOLD"

GREEN="$(tput setf 2)"
GREENB="$GREEN$BOLD"

AZURE="$(tput setf 3)"
AZUREB="$AZURE$BOLD"

RED="$(tput setf 4)"
REDB="$RED$BOLD"

PURPLE="$(tput setf 5)"
PURPLEB="$PURPLE$BOLD"

YELLOW="$(tput setf 6)"
YELLOWB="$YELLOW$BOLD"

WHITE="$(tput setf 7)"
WHITEB="$WHITE$BOLD"

NORMAL="$(tput sgr0)"

file=$(basename $0)
if [ $file = ".term_colors" ]; then
    echo -en "${BLUE}normal blue$NORMAL\t"
    echo "${BLUEB}bold blue$NORMAL"
    echo -en "${GREEN}normal green$NORMAL\t"
    echo "${GREENB}bold green$NORMAL"
    echo -en "${AZURE}normal azure$NORMAL\t"
    echo "${AZUREB}bold azure$NORMAL"
    echo -en "${RED}normal red$NORMAL\t"
    echo "${REDB}bold red$NORMAL"
    echo -en "${PURPLE}normal red$NORMAL\t"
    echo "${PURPLEB}bold red$NORMAL"
    echo -en "${YELLOW}normal yellow$NORMAL\t"
    echo "${YELLOWB}bold yellow$NORMAL"
    echo -en "${WHITE}normal white$NORMAL\t"
    echo "${WHITEB}bold white$NORMAL"
fi

# vim: ft=sh
